version: "3.8"
services:
    mysql:
        image: richardzhou666/mysql-bank:latest
        ports:
              - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password

    jar:
        image: richardzhou666/customer:latest
        ports:
            - "3333:8080"
        depends_on:
            - mysql